<div class="container" id="articleview">
    <h2 class="text-center">Arcane</h2>
    
    <p><i>Riot Games, l’une des plus grandes industries du jeu vidéo et notamment connu pour son jeu phare « League of Legends », se lance maintenant sur la création d’une série sur Netflix afin d’explorer d’autres champs de l’industrie du divertissement.</i></p>
       
        <h4>Le synopsis de la série</h4>
        <p>La série se centre sur l’histoire des deux sœurs, Vi et Powder, ayant passé toute leur enfance à vivre dans les bas-fonds de la cité de Piltover. Pour pouvoir vivre un jour à la surface, elles ont eu recours au vol et à la violence. Suite à un cambriolage qui a dégénéré, les deux jeunes filles sont prises pour cibles par la police armée de Piltover. Suite à cela, elles étaient loin de s’imaginer les conséquences qui allaient découler de leurs actes.</p>
       <h4> L’univers</h4>
        <p>Ce qui a le plus plu dans la série Arcane, c’est son esthétique stylisée et son ambition visuelle. Le studio d’animation français, Fortiche Production, a réussi à recréer un univers propre à League Of Legends, le but étant de plaire aux fans mais aussi aux plus curieux. Tout en mélangeant animation 3D et 2D, la série présente un univers très saisissant et très réaliste.</p>
        <p>Chaque scène est remplie de détails, que ce soit dans l’animation d’un simple objet, les accessoires des personnages, les paysages de la série ou encore une phrase prononcée dans une langue inconnue. Tous ces petits détails permettent une immersion totale dans l’univers et ainsi aux personnages d’évoluer dans un cadre prenant.</p>
        <p>L’histoire se centre principalement sur la relation délicate des sœurs Vi et Jinx, qui, très jeunes, ont souffert d’une guerre sanglante et ont perdu tout parent. On assiste à leur évolution dans cet univers complexe accompagné par différents personnages secondaires qui, chacun, ont une histoire assez bien développée dans la série.</p>
        <p>Chaque personnage se construit au fil de l’histoire, possédant leurs propres buts et leurs propres enjeux souvent liés à un traumatisme. La série traite différents sujets comme le sens de la famille, la lutte des classes, le progrès social, et la responsabilité envers les générations futures.</p>
        <p>Cette multitude de personnages peut créer une déception et nous éloigner du fil rouge de la série, à savoir la relation entre les deux sœurs, mais ces moments sont peu présents et la rythmique de la série n’est pas pour autant cassée.</p>
        <p>Arcane est une réussite en tout point, que ce soit au niveau de la réalisation visuelle, du scénario ou encore des bandes sons réalisées pour le film. Elle plaira autant aux fans de l’univers de League of Legends qu’à ceux qui ne connaissent rien du jeu vidéo.</p>

        <div id="commentaires">
            <h3 id="titre commentaire">Les derniers commentaires</h3>
            <p><b>Ines Rahali</b> - 06/02/2002<p<p>
                <p>Etant une grande fan de League of Legends depuis maintenant plusieurs années, j’ai été non seulement agréablement surprise par Netflix mais également par le studio d’animation français Fortiche Production qui ont su parfaitement adapter la série tirée du jeu vidéo que ce soit au niveau du graphisme ou du scénario. Un réel travail a été réalisé tout au long de la série, les paysages collent parfaitement à l’univers du jeu vidéo. Les personnages, aussi uniques soient-ils, évoluent tout au long de la série. Nous assistons, pour le cas de Vi, à une introspection et une évolution du personnage en essayant de donner le meilleur d’elle-même pour retrouver sa sœur et recoller les morceaux. Quant à Jinx, par contre, une vraie dégradation est créée tout autour du personnage qui, tout au long de la série, se détruit de plus en plus et sombre dans la folie qu’elle s’est créée elle-même. Les bandes sons de la série et l’environnement sont incroyables, ceux-ci nous plongent directement dans l’univers. J’ai adoré la série et la recommande à tous, que vous soyez joueurs de League of Legends ou non, la série a un grand potentiel pour plaire à un large public ! J’attends la saison 2 avec impatience.</p>
                <p><b>Cyril Rucart</b> - 06/02/2002<p<p>
                    <p>N'étant pas un grand fan de League of Legends et encore moins de ce que propose Riot Games en termes de jeux vidéos, j’ai quand même voulu m’intéresser à leur série par simple curiosité. J’avais également peur d’être complètement perdu dans l’histoire car ce n’est pas un univers que je connais. Cependant, j’ai toujours été passionné par l’animation que ce soit en film ou en série et étonnamment, la série m’a beaucoup plu dans l’ensemble. Les graphismes étaient à couper le souffle, encore une fois Fortiche Production a su montrer l’étendue de leur talent en créant une ambiance assez sombre et mature tout au long de la série ce qui ne m’a pas déplu. Les émotions des personnages étaient parfaitement représentées et étaient très expressives, je ne cache pas m’être senti assez émotif à certains moments de la série. Sachant que le studio travaille aux côtés de Riot Games depuis un moment maintenant et ont également réalisé plusieurs séries d’animations, je ne m’attendais pas moins de leur part. Ayant l’habitude de regarder mes séries en VO, j’ai voulu regarder Arcane en VF pour voir la qualité des doublages. Je ne cache pas que ceux-ci ne m’ont pas déplu. Les voix collent parfaitement avec les personnages et on ressent parfaitement leurs émotions à travers celles-ci. Pour résumer, n’ayez pas peur de vous lancer dans cette série même si vous ne faites pas du tout partie de l’univers, vous ne serez pas déçu et en ressortirez impressionnés. 

                    </p>
            </div>
    <div> 

