<div class="container" id="articleview">
    <h2 class="text-center">The Mandalorian</h2>
    
    <p><i>Après une trilogie de films Star Wars ayant reçu des critiques très mitigées, Disney revient en force avec la plateforme de streaming Disney + et compte bien s’en servir pour étendre grandement cet univers mythique.</i></p>
       
        <h4>Le synopsis de la série</h4>
        <p>The Mandalorian, la première série en prise de vue réelle dans l’univers de Star Wars, suit les aventures d’un chasseur de primes mandalorien surnommé Mando (Pedro Pascal) dont on ne connait ni le visage ni le nom et qui vit sa vie selon le credo de son clan, qui parcourt la galaxie et capture des criminels pour gagner sa vie. L’histoire prend place cinq ans après le dernier film de la trilogie originale, Le Retour du Jedi. Ce personnage évolue dans une société post-Empire qui essaye de se reconstruire après la mort du dirigeant tyrannique, l’Empereur Palpatine.
        </p>
        <p>Mais son quotidien est sur le point d’être bouleversé lorsqu’il accepte un contrat particulier avec un client qu’il doit rencontrer en face à face. Le client (Werner Herzog) est un ancien membre de l’Empire qui lui propose une quantité importante de beskar, le métal composant les armures mandaloriennes, dont la quasi-totalité avait été récupéré par l’Empire. Mando arrive finalement à sa cible qui n’est autre qu’un enfant avec qui il se lie d’affection. Il va tenter de le protéger de toutes les personnes s’en prenant à lui tout en essayant de découvrir pourquoi cet enfant est si convoité. Mando se fera quelques alliés en chemin comme Cara Dune (Gina Carano) et Greef Karga (Carl Weathers).
        </p>
       <h4> L’univers</h4>
        <p>L’univers de Star Wars a su attirer de nombreuses personnes depuis 1977 au cinéma, puis sur petit écran sous forme d’animation. C’est un des univers de science-fiction les plus populaires du monde, l’adapter au format de série télévisée n’est donc pas chose aisée. L’équipe derrière The Mandalorian menée par Jon Favreau réussit avec brio à transposer cet univers. 
        </p>
        <p>Disney a mis en place une toute nouvelle technologie de tournage appelé « Volume » qui consiste à diffuser sur un grand écran incurvé les décors de manière interactive par rapport au mouvement de caméra. De cette manière, les spectateurs sont directement propulsés dans l’univers et le rendu est très crédible. L’univers de Star Wars n’a jamais été aussi immersif que dans The Mandalorian. Ils ont également utilisé des marionnettes et des maquettes comme cela avait été fait à l’époque de la première trilogie, on retrouve vraiment les origines de la saga.</p>
        <p>La trame principale voit Le Mandalorien et L’Enfant voyager de planète en planète pour se sauver de l’Empire tout en aidant les différents personnages qu’ils rencontrent sur leur route. Une relation père-fils s’installe petit à petit entre les deux protagonistes. Le credo de Mando qui lui interdit d’enlever son casque est un vrai défi pour l’acteur qui arrive uniquement au travers de sa voix et de ses mouvements corporels parfois très subtils à nous faire ressentir les émotions de ce personnage qui ne manque pas de charisme.
        </p>
        <p>La série présente une histoire plus terre à terre que les films en s’inspirant grandement des westerns. On retrouve le thème de la famille qui a toujours été central dans les films Star Wars qui suivaient la famille Skywalker. On trouve également de nombreuses références au reste de la saga à travers certains décors, personnages et objets.
        </p>
        <p>Les nombreux personnages secondaires qui entrent en scène et accompagnent Mando dans son aventure sont relativement simples en termes de caractères mais aussi très efficaces et bien écrits.</p>
        <p>Ils font évoluer le personnage de Mando en le rapprochant de l’humanité et en le libérant des restrictions de son credo au fil des épisodes.</p>
        <p>The Mandalorian est un début très prometteur pour l’avenir de la saga sur petit écran qui est déjà bien fourni puisque Disney a annoncé d’autres saisons ainsi que d’autres séries dans l’univers comme Obi-Wan Kenobi, Ahsoka ou encore Le Livre de Boba Fett. La série saura ravir aussi bien les fans de la première heure que les personnes découvrant la saga grâce à celle-ci. C’est donc une grande réussite pour la plateforme de streaming de Disney. </p>

        <div id="commentaires">
            <h3 id="titre commentaire">Les derniers commentaires</h3>
            <p><b>Lucas Babin</b> - 06/02/2002<p<p>
                <p>En tant que fan de Star Wars depuis tout petit, je dois reconnaître que j’étais très sceptique à l’annonce de la série. Je ne suis vraiment pas fan de ce que Disney a fait de la saga au cinéma mais je dois avouer que là, ils ont fait très fort ! Baser une série entière sur un personnage qui ne manie pas la force et n’a pas de sabre laser est très audacieux et c’est un pari réussi selon moi. On découvre une nouvelle facette de cette galaxie lointaine, très lointaine, il est appréciable d’explorer d’autres histoires que celle de la famille Skywalker. La musique nous plonge directement dans l’ambiance Space Western de la série. Le compositeur Ludwig Göransson apporte un vent de fraîcheur tout en rendant hommage aux compositions originales de John Williams. Les effets spéciaux sont très convaincants pour une série télévisée et c’est un plaisir de voir que certaines techniques d’époque ont été réutilisées dans cette série. On ressent que les créateurs de la série sont de vrais fans et respectent vraiment l’œuvre originale de George Lucas. Je suis comblé et j’ai hâte de voir ce que Disney a en stock pour la suite !</p>
                <p><b>Timothée Hochin</b> - 06/02/2002<p<p>
                    <p>Je n’ai jamais été un grand fan de Star Wars, je n’ai regardé qu’un ou deux films de la saga et ils ne m’ont jamais captivé, alors lorsque l’on m’a parlé d’une série issue de cet univers autant vous dire que çe ne m’a fait ni chaud ni froid. Mais à force d’en entendre parler, ma curiosité à été piqué et j’ai donc regardé The Mandalorian. Je n’aurai jamais pensé dire ça un jour et pourtant, j’ai adoré cette série. Un scénario bien ficelé qui nous tient en haleine tout du long, des personnages attachants, de l’action bien rythmée et des effets spéciaux réussis. Cette série à tout pour plaire. On ressent le lien existant avec les films mais ils ne sont pas indispensables pour comprendre et apprécier l’histoire racontée ici. Les plans et l’univers rappellent notamment les anciens westerns et les films de samouraïs de Kurosawa aussi bien dans leurs ambiances que dans les chorégraphies de combats et les différentes interactions entre les personnages. Pour les personnes comme moi qui ne veulent pas entendre parler des films Star Wars, pas de panique, il n’y a pas l’ombre d’un Dark Vador ou d’un R2-D2 ici. En bref, que vous aimiez la saga ou pas, foncez !
                    </p>
            </div>
    <div> 